baseURL = "https://dataprivacymemo.com"
languageCode = "en-us"
title = "Data Privacy Memo"
theme = "PaperMod"

[params]
    author = "David Friedman"
    description = "Data protection law insights across US and EU"
    keywords = ["privacy", "GDPR", "data protection", "legal tech"]
    ShowTags = true
    ShowCategories = true
    numberOfTagsToShow = 10
    numberOfCategoriesToShow = 5
    copyright = "© 2025 David Friedman - Data Privacy Memo"
    
    # New comments configuration
    comments = true
    commentForm = true

[taxonomies]
    category = "categories"
    tag = "tags"

[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about"
    weight = 10

  [[menu.main]]
    identifier = "categories"
    name = "Categories"
    url = "/categories"
    weight = 20

  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags"
    weight = 30

  [[menu.main]]
    identifier = "rss"
    name = "RSS Feed"
    url = "/index.xml"
    weight = 40

# RSS Configuration
rssLimit = 10
[outputs]
    home = ["HTML", "RSS", "JSON"]

[services]
    [services.rss]
        limit = 10