baseURL = "https://dataprivacymemo.com"
languageCode = "en-us"
title = "Data Privacy Memo"
theme = "PaperMod"

[params]
    author = "David Friedman"
    description = "Data protection law insights across US and EU"
    keywords = ["privacy", "GDPR", "data protection", "legal tech"]
    ShowTags = true
    ShowCategories = true
    numberOfTagsToShow = 10
    numberOfCategoriesToShow = 5
    copyright = "© 2025 David Friedman - Data Privacy Memo"
    
    # Added settings for descriptions/excerpts
    showFullTextInMainFeed = false
    summaryLength = 0  # Setting to 0 disables automatic summaries
    
    # PaperMod specific settings for descriptions
    hideDescriptionInList = false
    ShowReadingTime = true
    ShowShareButtons = false
    ShowPostNavLinks = true
    ShowBreadCrumbs = true
    ShowCodeCopyButtons = true
    UseHugoToc = true
    
    # Social Icons
    [[params.socialIcons]]
    name = "bluesky"
    url = "https://bsky.app/profile/dataprivacymemo.bsky.social"

[taxonomies]
    category = "categories"
    tag = "tags"

[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about"
    weight = 10

  [[menu.main]]
    identifier = "rss"
    name = "RSS Feed"
    url = "/index.xml"
    weight = 20

# RSS Configuration
rssLimit = 10
[outputs]
    home = ["HTML", "RSS", "JSON"]

[services]
    [services.rss]
        limit = 10