# Staticman configuration for Data Privacy Memo

[comments]
    # Enable comment moderation
    moderation = true

    # Allowed fields in the comment form
    allowedFields = ["name", "message"]

    # Required fields
    requiredFields = ["name", "message"]

    # Spam protection
    [comments.akismet]
        enabled = true

    # Customize comment storage
    [comments.generatedFields]
        [comments.generatedFields.date]
            type = "date"
            [comments.generatedFields.date.options]
                format = "timestamp-seconds"

    # Limit comment length
    [[comments.transforms]]
        type = "truncate"
        max = 500

# Notification settings (optional)
[notifications]
    enabled = false

# Commit message for new comments
commitMessage = "New comment on Data Privacy Memo"